# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

image: debian/stable

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

sources:
  - https://git.sr.ht/~wombelix/aws-neuron-driver-publish-source
  - https://git.sr.ht/~wombelix/build-helper-scripts

secrets:
  - 5b076ab5-1361-4d71-905b-4ff8c836c62c

environment:
  GIT_MIRROR_SSH_KEY: ~/.ssh/5b076ab5-1361-4d71-905b-4ff8c836c62c
  GIT_MIRROR_GITHUB: git@github.com:wombelix/aws-neuron-driver-publish-source.git
  GIT_MIRROR_GITLAB: git@gitlab.com:wombelix/aws-neuron-driver-publish-source.git
  GIT_MIRROR_CODEBERG: git@codeberg.org:wombelix/aws-neuron-driver-publish-source.git
  GO111MODULE: 'on'

tasks:
  - mirror: |
      cd build-helper-scripts
      source git-mirror.sh
      cd ..

      cd aws-neuron-driver-publish-source

      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITHUB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITLAB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_CODEBERG"

triggers:
  - action: email
    condition: failure
    to: dominik@wombacher.cc
